[build]
  publish = "public"          # Directory to deploy
  functions = "netlify/functions"  # Directory for serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
